// <auto-generated />
using Formicarium.Dashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Formicarium.Dashboard.Data.Migrations
{
    [DbContext(typeof(FormicariumDbContext))]
    partial class FormicariumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Formicarium.Dashboard.Data.BuildProgressEntry", b =>
                {
                    b.Property<int>("Step")
                        .HasColumnType("int");

                    b.Property<long>("CompletedAt")
                        .HasColumnType("bigint");

                    b.HasKey("Step");

                    b.ToTable("BuildProgress");
                });

            modelBuilder.Entity("Formicarium.Dashboard.Data.RiserSample", b =>
                {
                    b.Property<long>("Ts")
                        .HasColumnType("bigint");

                    b.Property<int>("Riser")
                        .HasColumnType("int");

                    b.Property<double>("Brightness")
                        .HasColumnType("float");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<long>("Crossings")
                        .HasColumnType("bigint");

                    b.Property<long>("Cumulative")
                        .HasColumnType("bigint");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.HasKey("Ts", "Riser");

                    b.HasIndex("Channel");

                    b.HasIndex("DayNumber", "Riser");

                    b.ToTable("RiserSamples");
                });

            modelBuilder.Entity("Formicarium.Dashboard.Data.Sample", b =>
                {
                    b.Property<long>("Ts")
                        .HasColumnType("bigint");

                    b.Property<bool>("Fan")
                        .HasColumnType("bit");

                    b.Property<int>("Faults")
                        .HasColumnType("int");

                    b.Property<bool>("Feed")
                        .HasColumnType("bit");

                    b.Property<bool>("Heater")
                        .HasColumnType("bit");

                    b.Property<int>("LightingMode")
                        .HasColumnType("int");

                    b.Property<double?>("NestBottomC")
                        .HasColumnType("float");

                    b.Property<bool>("NestFan")
                        .HasColumnType("bit");

                    b.Property<double?>("NestRh")
                        .HasColumnType("float");

                    b.Property<double?>("NestTopC")
                        .HasColumnType("float");

                    b.Property<double?>("OutworldC")
                        .HasColumnType("float");

                    b.Property<double?>("OutworldRh")
                        .HasColumnType("float");

                    b.Property<bool>("Refill")
                        .HasColumnType("bit");

                    b.Property<double?>("SoilPct")
                        .HasColumnType("float");

                    b.HasKey("Ts");

                    b.ToTable("Samples");
                });
#pragma warning restore 612, 618
        }
    }
}
